Feature 2
b-bodnar/company-employees pull request #2
Opened 2021-02-23 16:11 UTC by b-bodnar

# PR Details

Added two SQL files with DDL and DML scripts.

2021-02-23 16:51 UTC, Andriireva requested changes

2021-02-23 16:51 UTC, Andriireva commented on task_1_create_db_and_tables.sql
> +    `id`   bigint      NOT NULL AUTO_INCREMENT,
type should by bigserrial and without AUTO_INCREMENT

2021-02-23 16:51 UTC, Andriireva commented on task_1_create_db_and_tables.sql
> +    `id`            BIGINT      NOT NULL AUTO_INCREMENT,
same as above

2021-02-23 16:51 UTC, Andriireva commented on task_1_create_db_and_tables.sql
> +    `married`                    TINYINT NULL,
there is type boolean in PostgresSQL

2021-02-23 16:51 UTC, Andriireva commented on task_1_create_db_and_tables.sql
> +    `id`                         BIGINT NOT NULL AUTO_INCREMENT,
save as above

2021-03-01 18:06 UTC, b-bodnar commented on task_1_create_db_and_tables.sql
> +    `id`   bigint      NOT NULL AUTO_INCREMENT,
Fixed

2021-03-01 18:07 UTC, b-bodnar commented on task_1_create_db_and_tables.sql
> +    `id`            BIGINT      NOT NULL AUTO_INCREMENT,
Fixed

2021-03-01 18:07 UTC, b-bodnar commented on task_1_create_db_and_tables.sql
> +    `married`                    TINYINT NULL,
Fixed

2021-03-01 18:07 UTC, b-bodnar commented on task_1_create_db_and_tables.sql
> +    `id`                         BIGINT NOT NULL AUTO_INCREMENT,
Fixed

2021-03-02 15:43 UTC, Andriireva approved these changes

2021-03-02 15:44 UTC, merged